autoclip: false
autoimport: true
cliptimeout: 15
exportkeys: false
mime: true
nocolor: false
nopager: false
notifications: false
path: /Users/daniels/.password-store
safecontent: false
mounts:
  personal: /Users/daniels/.password-store-personal
