root:
  askformore: false
  autoimport: true
  autosync: true
  cliptimeout: 15
  noconfirm: false
  nopager: false
  path: /Users/StroDa/.password-store
  safecontent: false
  usesymbols: false
  nocolor: false
  notifyunclip: false
mounts:
  personal:
    askformore: false
    autoimport: true
    autosync: true
    cliptimeout: 15
    noconfirm: false
    nopager: false
    path: /Users/StroDa/.password-store-personal
    safecontent: false
    usesymbols: false
    nocolor: false
    notifyunclip: false
version: 1.6.9
