root:
  askformore: false
  autoimport: true
  autosync: true
  cliptimeout: 15
  cryptobackend: gpg
  nocolor: false
  noconfirm: false
  nopager: false
  path: ~/.password-store
  safecontent: false
  storebackend: fs
  syncbackend: git
  usesymbols: false
  nocolor: false
  notify: false
mounts:
  personal:
    askformore: false
    autoimport: true
    autosync: true
    cliptimeout: 15
    cryptobackend: gpg
    nocolor: false
    noconfirm: false
    nopager: false
    path: ~/.password-store-personal
    safecontent: false
    storebackend: fs
    syncbackend: git
    usesymbols: false
    nocolor: false
    notify: false
version: 1.6.11
